### ISSUE TITLE
The doPlayerTeleport event can be abused to teleport players through walls

### ISSUE THREAD

**Issue by LakeYS** [cityrpg/CityRPG-4-Alpha#16]
Using the "Relative" option, players can teleport themselves through walls using the doPlayerTeleport option.

The easy solution would be to simply override the relative option in a package hook, however I'd like to try de-registering and re-registering it to remove the option from the interface.

**Comment by Dglider** [comment]
I believe registering overwrites the old entry.  At least that's what it screams at me in the console whenever I do it.

**Comment by LakeYS** [comment]
Can un-register it using unRegisterOutputEvent, I'm going to give this a shot shortly.. If all else fails, it's also possible to [manipulate the values directly](https://github.com/Electrk/bl-decompiled/blob/5ea86a1e4f71cb92799bdc1305ba062771c5867e/server/scripts/allGameScripts/events/output/registerOutputEvent.cs) and refresh the event tables.
